MenuMaker/Models/MenuViewModel.cs
using MenuMaker.Data;
using System.Collections.Generic;

namespace MenuMaker.Models
{
    public class MenuViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int PersonsCount { get; set; }
        public string UserId { get; set; }
        public ApplicationUser User { get; set; }
        public List<DayViewModel> Days { get; set; }
        public ICollection<MenuRecipeViewModel> MenuRecipes { get; set; }

        public List<RecipeViewModel> RecipeViewModelsDropdownList { get; set; }
    }
}

MenuMaker/Controllers/MenuController.cs
using AutoMapper;
using MenuMaker.Business.Interfaces;
using MenuMaker.Business.Models;
using MenuMaker.Models;
using Rotativa;
using System.Collections;
using System.Collections.Generic;
using System.Web.Mvc;

namespace MenuMaker.Controllers
{
    [Authorize(Roles = "admin")]

    public class MenuController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IMenuManager _menuManager;
        private readonly IDayManager _dayManager;

        private readonly IRecipeManager _recipeManager;

        public MenuController(IMapper mapper, IMenuManager menuManager,
            IRecipeManager recipeManager, IDayManager dayManager)
        {
            _mapper = mapper;
            _menuManager = menuManager;
            _recipeManager = recipeManager;
            _dayManager = dayManager;
        }

        // GET: Menu
        public ActionResult Index()
        {
            var menuModelsList = _menuManager.GetAll();
            var menuViewModelsList = _mapper.Map<IEnumerable<MenuIndexViewModel>>(menuModelsList);
            return View(menuViewModelsList);
        }

        // GET: Menu/Create
        public ActionResult Create()
        {
            var newMenu = new MenuCreateViewModel();
            var recipeModelsDropdownList = _recipeManager.GetAll();
            var recipeViewModelsDropdownList = _mapper.Map<List<RecipeViewModel>>(recipeModelsDropdownList);
            newMenu.RecipeViewModelsDropdownList = recipeViewModelsDropdownList;

            newMenu.Days = _mapper.Map<List<DayViewModel>>(_dayManager.GetAll());

            return View(newMenu);
        }

        [HttpPost]
        public ActionResult Create(MenuPostViewModel menuPostViewModel)
        {
            if (ModelState.IsValid)
            {
                var menuCreateModel = _mapper.Map<MenuCreateModel>(menuPostViewModel);
                var menuId = _menuManager.Create(menuCreateModel);

                if (menuPostViewModel.DayId.Length != menuPostViewModel.RecipeId.Length)
                {
                    return new HttpStatusCodeResult(400);
                }

                return RedirectToAction("Details/" + menuId);
            }
            return View(menuPostViewModel);
        }

        // GET: Menu/Delete/5
        public ActionResult Delete(int id)
        {
            _menuManager.Remove(id);
            return RedirectToAction("Index");
        }

        // GET: Menu/Details/5
        public ActionResult Details(int id)
        {
            MenuModel menuModel = _menuManager.FindById(id);

            if (menuModel == null)
            {
                return HttpNotFound();
            }

            var menuViewModel = _mapper.Map<MenuViewModel>(menuModel);

            menuViewModel.Days = _mapper.Map<List<DayViewModel>>(_dayManager.GetAll());

            return View(menuViewModel);
        }

        public ActionResult Edit(int id)
        {
            var menuModel = _menuManager.FindById(id);
            if (menuModel == null)
            {
                return HttpNotFound();
            }

            var menuEditVM = _mapper.Map<MenuEditVM>(menuModel);

            var recipeModelsDropdownList = _recipeManager.GetAll();
            var recipeViewModelsDropdownList = _mapper.Map<List<RecipeViewModel>>(recipeModelsDropdownList);
            menuEditVM.RecipeViewModelsDropdownList = recipeViewModelsDropdownList;

            menuEditVM.Days = _mapper.Map<List<DayViewModel>>(_dayManager.GetAll());
            return View(menuEditVM);
        }

        [HttpPost]
        public ActionResult Edit(MenuEditPM menuEditPM)
        {

            if (ModelState.IsValid)
            {
                var menuEditModel = _mapper.Map<MenuEditModel>(menuEditPM);
                _menuManager.Update(menuEditModel);

                return RedirectToAction("Details/" + menuEditPM.Id);
            }

            var menuModel = _menuManager.FindById(menuEditPM.Id);
            var menuEditVM = _mapper.Map<MenuEditVM>(menuModel);

            return View(menuEditVM);
        }

        public ActionResult GenerateBuyList(int id)
        {
            var buyModels = _menuManager.GetBuyList(id);
            var buyViewModels = _mapper.Map<IEnumerable<BuyListViewModel>>(buyModels);
            return View(buyViewModels);
        }

        public ActionResult GetPDF(int id)
        {
            var buyModels = _menuManager.GetBuyList(id);
            var buyViewModels = _mapper.Map<IEnumerable<BuyListViewModel>>(buyModels);

            return new ViewAsPdf("GenerateBuyList", buyViewModels);
        }
    }
}

MenuMaker/Controllers/RecipeController.cs
using AutoMapper;
using MenuMaker.Business.Interfaces;
using MenuMaker.Business.Models;
using MenuMaker.Data.Models;
using MenuMaker.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Web.Mvc;

namespace MenuMaker.Controllers
{
    [Authorize(Roles="superUser")]
    public class RecipeController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IRecipeManager _recipeManager;
        private readonly IIngredientManager _ingredientManager;

        public RecipeController(IMapper mapper, IRecipeManager recipeManager, IIngredientManager ingredientManager)
        {
            _mapper = mapper;
            _ingredientManager = ingredientManager;
            _recipeManager = recipeManager;
        }

        // GET: Recipe
        public ActionResult Index()
        {
            var recipeList = _recipeManager.GetAll();
            var listOfIngredientsViewModels = _mapper.Map<IList<RecipeViewModel>>(recipeList);

            return View(listOfIngredientsViewModels);
        }

        // GET: Recipe/Details/5
        public ActionResult Details(int id)
        {
            var recipeModel = _recipeManager.FindById(id);

            if (recipeModel == null)
            {
                return HttpNotFound();
            }

            var recipeViewModel = _mapper.Map<RecipeViewModel>(recipeModel);
            return View(recipeViewModel);
        }

        // GET: Recipe/Create
        public ActionResult Create()
        {
            var newRecipe = new RecipeIngredientsViewModel();

            var dropDownListOfIngredientModels = _ingredientManager.GetAll();
            var dropDownListOfIngrediens = _mapper.Map<List<IngredientViewModel>>(dropDownListOfIngredientModels);
            newRecipe.IngredientsDropDownList = dropDownListOfIngrediens;

            return View(newRecipe);
        }

        // POST: Recipe/Create
        [HttpPost]
        public ActionResult Create(CreatedRecipePostModel createdRecipePostVM)
        {
            if (ModelState.IsValid)
            {
                if (createdRecipePostVM.ImageFile != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(createdRecipePostVM.ImageFile.FileName);
                    string extension = Path.GetExtension(createdRecipePostVM.ImageFile.FileName);
                    fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    var path = Path.Combine(Server.MapPath("~/Images/"), fileName);
                    createdRecipePostVM.ImageFile.SaveAs(path);
                    createdRecipePostVM.ImagePath = "~/Images/" + fileName;
                }

                var createdRecipeModel = _mapper.Map<CreatedRecipeModel>(createdRecipePostVM);
                _recipeManager.Create(createdRecipeModel);

                return RedirectToAction("Index");
            }

            return View(createdRecipePostVM);
        }

        // GET: RecipeViewModels/Edit/5
        public ActionResult Edit(int id)
        {
            var recipeModel = _recipeManager.FindById(id);
            var recipeViewModel = _mapper.Map<RecipeViewModel>(recipeModel);

            if (recipeViewModel == null)
            {
                return HttpNotFound();
            }

            recipeViewModel.IngredientsDropDownList = _mapper.Map<List<IngredientViewModel>>( _ingredientManager.GetAll());

            return View(recipeViewModel);
        }

        // POST: RecipeViewModels/Edit/5
        [HttpPost]
        public ActionResult Edit(CreatedRecipePostModel recipeViewModel)
        {
            if (ModelState.IsValid)
            {
                if (recipeViewModel.ImageFile != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(recipeViewModel.ImageFile.FileName);
                    string extension = Path.GetExtension(recipeViewModel.ImageFile.FileName);
                    fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    var path = Path.Combine(Server.MapPath("~/Images/"), fileName);
                    recipeViewModel.ImageFile.SaveAs(path);
                    recipeViewModel.ImagePath = "~/Images/" + fileName;
                }
                var recipeModel = _mapper.Map<CreatedRecipeModel>(recipeViewModel);

                _recipeManager.Update(recipeModel);

                return RedirectToAction("Index");
            }
            return View(recipeViewModel);
        }

        // GET: RecipeViewModels/Delete/5
        public ActionResult Delete(int id)
        {
            _recipeManager.Remove(id);
            return RedirectToAction("Index");
        }
    }
}

MenuMaker/Views/Menu/Create.cshtml
@model MenuMaker.Models.MenuCreateViewModel

@{
    ViewBag.Title = "Create";
    var weekDays = Model.Days;
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>MenuViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", name = "IngredientName" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", rows = "5" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PersonsCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PersonsCount, new { htmlAttributes = new { @class = "form-control", name = "PersonsCount", type = "number", min = 1, value = 1 } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>


        @foreach (var day in weekDays)
        {
            var recipeDropdownSelectList = new SelectList(Model.RecipeViewModelsDropdownList, "id", "name");

            <div class="form-group">
                <h4>
                    @Html.Label(day.Name, new { @class = "control-label col-md-2" })
                </h4>
            </div>
            <div class="week-day">
                <div class="hidden">
                    <div class="recipe-input-fields">

                        @{
                            var recipeDropdownSelectList2 = new SelectList(Model.RecipeViewModelsDropdownList, "id", "name");
                        }
                        <div class="form-group">
                            @Html.Label("RecipeId", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("RecipeId", recipeDropdownSelectList2, "-No recipe selected-", htmlAttributes: new { @class = "form-control" })
                                <input name="DayId" value=@day.Id hidden />
                                <button type="button" class="btn btn-default" style='width:120px' onclick="Remove(this)">Remove</button>
                            </div>
                        </div>

                    </div>
                </div>
                <div class="recipe-input-fields">
                    <div class="form-group">
                        @Html.Label("RecipeId", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownList("RecipeId", recipeDropdownSelectList, "-No recipe selected-", htmlAttributes: new { @class = "form-control" })
                            <button type="button" class="btn btn-default" style='width:120px' onclick="Remove(this)">Remove</button>
                            <input name="DayId" value=@day.Id hidden />
                        </div>
                    </div>

                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="button" value="Add recipe" class="btn btn-default" style='width:120px' onclick="GetDynamicRecipeInputFields(this)" />
                    </div>
                </div>
            </div>
        }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="@Url.Content("~/Content/Controllers/MenuController/input-area.js")"></script>
}

MenuMaker/Views/Menu/DayCellPartView.cshtml
@model IEnumerable<MenuMaker.Models.MenuRecipeViewModel>

@foreach (var item in Model)
{
    <dd>
        @item.Recipe.Name
    </dd>
}

MenuMaker/Views/Menu/Details.cshtml
@model MenuMaker.Models.MenuViewModel

@{
    ViewBag.Title = "Details";
    var weekDays = Model.Days;
}

<h2>Details</h2>

<div>
    <h4>MenuViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PersonsCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PersonsCount)
        </dd>

        @foreach (var weekDay in weekDays)
        {
            var currentDayRecipes = Model.MenuRecipes.Where(i => i.DayId == weekDay.Id).ToList();
            <dt>
                @weekDay.Name
            </dt>
            if (currentDayRecipes != null)
            {
                @Html.Partial("DayCellPartView", currentDayRecipes);
            }
            else
            {
                <dd>
                    @Html.Label("No meal for this day");
                </dd>
            }
        }
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index") |
    @Html.ActionLink("Generate buy list", "GenerateBuyList", new { id = Model.Id })
</div>

MenuMaker/Views/Menu/Edit.cshtml
@model MenuMaker.Models.MenuEditVM

@section Scripts {
    <script src="@Url.Content("~/Content/Controllers/MenuController/input-area.js")"></script>
}

@{
    ViewBag.Title = "Edit";
    var weekDays = Model.Days;
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>MenuViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", rows = "5" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PersonsCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PersonsCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PersonsCount, "", new { @class = "text-danger" })
            </div>
        </div>

        @foreach (var day in weekDays)
        {
            <div class="form-group">
                <h4>
                    @Html.Label(day.Name, new { @class = "control-label col-md-2" })
                </h4>
            </div>
            <div class="week-day">
                <div class="hidden">
                    <div class="recipe-input-fields">

                        @{
                            var recipeDropdownSelectList2 = new SelectList(Model.RecipeViewModelsDropdownList, "id", "name");
                        }
                        <div class="form-group">
                            @Html.Label("RecipeId", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("RecipeId", recipeDropdownSelectList2, "-No recipe selected-", htmlAttributes: new { @class = "form-control" })
                                <input name="DayId" value=@day.Id hidden />
                                <button type="button" class="btn btn-default" style='width:120px' onclick="Remove(this)">Remove</button>
                            </div>
                        </div>

                    </div>
                </div>
                <div class="recipe-input-fields">
                    @foreach (var menuRecipe in Model.MenuRecipes.Where(i => i.DayId == day.Id).ToList())
                    {
                        var recipeDropdownSelectList = new SelectList(Model.RecipeViewModelsDropdownList, "id", "name", menuRecipe.RecipeId);

                        <div class="form-group">
                            @Html.Label("RecipeId", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("RecipeId", recipeDropdownSelectList, "-No recipe selected-", htmlAttributes: new { @class = "form-control" })
                                <button type="button" class="btn btn-default" style='width:120px' onclick="Remove(this)">Remove</button>
                                <input name="DayId" value=@day.Id hidden />
                            </div>
                        </div>
                    }
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="button" value="Add recipe" class="btn btn-default" style='width:120px' onclick="GetDynamicRecipeInputFields(this)" />
                    </div>
                </div>
            </div>
        }


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MenuMaker/Views/Menu/GenerateBuyList.cshtml
@model IEnumerable<MenuMaker.Models.BuyListViewModel>

@{
    ViewBag.Title = "GenerateBuyList";
    //Layout = "_BuyListLayout.cshtml";
}

<h2>BuyList for menu #@Model.FirstOrDefault().MenuId</h2>

<table class="table" width="800px">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Amount)
        </th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
        </tr>
    }

</table>

<div class="form-group">  
        @Html.ActionLink("Get PDF", "GetPDF", new { id = Model.FirstOrDefault().MenuId }, new {target="_blank", @class="btn btn-success" })
</div>

MenuMaker/Views/Menu/Index.cshtml
@model IEnumerable<MenuMaker.Models.MenuIndexViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

MenuMaker/Views/Menu/RecipesInDayPartWiev.cshtml
@model IEnumerable<MenuMaker.Models.MenuRecipeViewModel>

@foreach (var item in Model)
{
    @item.Recipe.Name
}

MenuMaker/Views/Menu/_BuyListLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/content/my-navbar.css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index", "Home")" class="navbar-brand">
                    <img height="23" width="23" src="~/Images/homeButton.png" title="title" alt="additional title" />
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <div class="my-dropdown">
                            <button class="my-dropbtn">
                                Menues
                                <i class="fa fa-caret-down"></i>
                            </button>
                            <div class="my-dropdown-content">
                                @Html.ActionLink("View all", "Index", "Menu")
                                @Html.ActionLink("Add new", "Create", "Menu")
                                <a href="#">My menues</a>
                            </div>
                        </div>
                    </li>

                    <li>
                        <div class="my-dropdown">
                            <button class="my-dropbtn">
                                Recipes
                            </button>
                            <div class="my-dropdown-content">
                                @Html.ActionLink("View all", "Index", "Recipe")
                                <a href="#">My recepies</a>
                                @Html.ActionLink("Add new", "Create", "Recipe")
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="my-dropdown">
                            <button class="my-dropbtn">
                                Ingredients
                            </button>
                            <div class="my-dropdown-content">
                                @Html.ActionLink("View all", "Index", "Ingredient")
                                <a href="#">My ingredients</a>
                                @Html.ActionLink("Add new", "Create", "Ingredient")
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="my-dropdown">
                            <button class="my-dropbtn">
                                Users
                            </button>
                            <div class="my-dropdown-content">
                                <a href="#">Change user's role</a>
                                <a href="#">Remove user</a>
                                <a href="#">Ban user</a>
                            </div>
                        </div>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>